config/routes.rb
Rails.application.routes.draw do

  resources :categories

  get 'employersessions/new'

  match '/postJobs' => 'jobs#new', via: :post
  match '/signup' => 'users#new', via: :post
  match '/signin' => 'sessions#new', via: :get
  match '/signout' => 'sessions#destroy', via: :delete
  match '/searchJobs' => 'jobs#search', via: :get
  match '/searchForm' => 'jobs#searchForm', via: :get
  match '/jobList' => 'jobs#indexUser', via: :get
  match '/addEmp' => 'employers#new', via: :get
  match '/viewJobApplicants' => 'jobapplications#indexEmp', via: :get
  match '/admin/signup' => 'admins#new', via: :get
  match '/admin/signin' => 'admin_sessions#new', via: :get
  match '/admin/signout' => 'admin_sessions#destroy', via: :delete
  match '/searchPublic' => 'jobs#searchFormPublic', via: :get
  match '/searchPublicJobs' => 'jobs#searchPublic', via: :get
  match '/recommed'=>'jobs#recommend',via: :get

  root 'home#index'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :jobs
  resources :jobapplications
  resources :employers
  resources :employersessions, :only => [:new, :create, :destroy]
  resources :admins
  resources :admin_sessions, :only => [:new, :create, :destroy]
  resources :home

end

app/models/job.rb
class Job < ActiveRecord::Base

  #belongs_to :employer
  validates :job_ID, :presence => true

  validates :emp_name, :presence => true

  validates :title, :presence => true
  validates :description, :presence => true
  validates :tags, :presence => true

  validates :deadline, :presence => true

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @title = "All Jobs"
    #@jobs = Job.paginate(:page => params[:page])
    @jobs = Job.where('emp_name = ?',session[:emp_name])
    session[:empUser] = request.original_url
  end

  def indexUser
    @title = "All Jobs You have Applied To:"
    @jobs = Job.paginate(:page => params[:page])
  end


  def searchForm
    @job = Job.new
    @title = "Search Jobs"
  end

  def search
    if params[:one] == "1"
    #@job = Job.find_by_sql("select * from jobs where emp_name = '"+params[:keyword]+"'")
    @job = Job.where('deadline > ?', DateTime.now).where('emp_name = ?', params[:keyword])
    elsif params[:two] == "1"
    @job = Job.where('deadline > ?', DateTime.now).where('title = ?', params[:keyword])
    else
    @job = Job.where('deadline > ?', DateTime.now).where('tags = ?', params[:keyword])
    end

    session[:searchURL] = request.original_url
    #@job = Job.where({:emp_name => params[:search][:emp_name]}).all
  end
  def recommend
    Jobapplication.all.each do|user|
      if user.email==session[:userEmail]
        @content=user.tags
      end
    end
  @jobs=Job.where('deadline > ?',DateTime.now).where('tags=?',@content)
  end


  def searchFormPublic
    @job = Job.new
    @title = "Search Jobs"
  end

  def searchPublic
    if params[:one] == "1"
      @job = Job.find_by_sql("select * from jobs where emp_name = '"+params[:keyword]+"' AND public = '"+ "1" +"'")
    elsif params[:two] == "1"
      @job = Job.find_by_sql("select * from jobs where title = '"+params[:keyword]+"' AND public = '"+ "1" +"' ")
    else
      @job = Job.find_by_sql("select * from jobs where tags = '"+params[:keyword]+"' AND public = '"+ "1" +"' ")
    end

    session[:searchURL] = request.original_url
    #@job = Job.where({:emp_name => params[:search][:emp_name]}).all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
    @title = "Post a Job"
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:success] = "You have posted the job successfully!!"
      session[:empMail] = @job.emp_name
      EmployerNotifier.send_jobsubmit_email(@job).deliver
      redirect_to session[:employer]
    else
      @title = "Post a Job"
      render 'jobs/new'
    end
  end

  def edit
    @job = Job.find(params[:id])
    @title = "Edit Job"
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(job_params)
      flash[:success] = "Job updated."
      redirect_to session[:empUser]
    else
      @title = "Edit Job"
      render 'edit'
    end
  end

  def destroy
    Job.find(params[:id]).destroy
    flash[:success] = "Job Deleted Successfully."
    redirect_to jobs_path
  end





  private

  def job_params
    params.require(:job).permit(:job_ID, :emp_name, :title, :description, :tags, :deadline, :search, :category, :public)
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb

<div id="wrap">
  <div id="header">
<h1>Edit Job</h1>
    </div>

<%= simple_form_for(@job) do |f| %>
      <%= f.input :job_ID %>
      <%= f.input :emp_name %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :tags %>
      <%= f.input :deadline %>
      <%= f.input :category, collection: Category.pluck(:category) %>
      <%= f.input :public %>
      <%= f.button :submit, "Update Job" %>
<% end %>
<br/>
<div id="nav">
<li><%= link_to "Back To View Jobs", session[:empUser], :method => :get %></li>
</div>
    </div>

app/views/jobs/index.html.erb

<div id="wrap">
  <div id="header">
<h1>All Jobs Posted</h1>
    </div>
<div id="sidebar">


  <%= table_for @jobs, class: 'table' do |t| %>
    <% t.column :emp_name, 'Company' %>
    <% t.column :job_ID, 'Job ID' %>
    <% t.column :title, 'Title' %>
    <% t.column :deadline, 'Deadline' %>
    <% t.column :actions do |job| %>
      <%= link_to "Edit", "/jobs/#{job.id}/edit", :method => :get %> |
      <%= link_to "Delete", job, :method => :delete, :confirm => "You sure?",
                  :title => "Delete #{job.job_ID} of #{job.emp_name}" %>
    <% end %>
  <% end %>

  </div>
  <br/>
<div id="nav">
<li><%= link_to "Back Home Page", session[:employer], :method => :get %></li>
</div>
    </div>

app/views/jobs/indexUser.html.erb

<div id="wrap">
  <div id="header">
<h1>All Jobs Posted</h1>
    </div>

<%= will_paginate %>
  <div id="sidebar">
<ul class="users">
  <% @jobs.each do |job| %>
      <li>
        <%= job.emp_name%>
        </br>
        <%= job.job_ID%>
        <p>Apply for this Job!!!</p>
      </li>
  <% end %>
</ul>
    </div>
  </div>


<%= will_paginate %>

app/views/jobs/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<div id="wrap">
  <div id="header">
<h1>Post a Job</h1>
</div>
<%= simple_form_for(@job) do |f| %>
      <%= f.input :job_ID %>
      <%= f.input :emp_name %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :tags, label: 'Tags (eg: Intern, Full Time)' %>
      <%= f.input :deadline, label: 'deadline (YYYY-MM-DD)' %>
      <%= f.input :category, collection: Category.pluck(:category) %>
      <%= f.input :public, label: 'public (eg: 1 for Public and 0 for Private)' %>
      <%= f.button :submit, "Post a Job" %>
<% end %>
<br/>

<div id = "nav">
<br/>
<li><%= link_to "Back To Home Page", session[:employer], :method => :get %></li>
<li><%= link_to "View Available Categories", categories_path, :method => :get %></li>
</div>
</div>
</body>
</html>

app/views/jobs/recommend.html.erb
<div id=wrap">
  <div id="header"><h1>Recommended Jobs For you !!!</h1></div>
  <div id="sidebar">
   <% @jobs.each do |r| %>


     <li><strong>Company Name : </strong><%= r.emp_name %>
     <strong>Job Title : </strong><%= r.title%>

      <strong>Job ID : </strong><%= r.job_ID%>
      </li>

    <br/>
<li><%= link_to "Apply for this Job", new_jobapplication_path, :method => :get %></li>
<% end%>
</div>
<div id="nav">
<li><%= link_to "Back To Home Page", session[:userHP], :method => :get %></li>
</div>
</div>

app/views/jobs/search.html.erb
<div id="wrap">
<% @job.each do |r| %>
    <table>
    <tr>
      <td><strong>Company Name : </strong><%= r.emp_name %></td></tr>
      <tr> <td><strong>Job Title : </strong><%= r.title%></td></tr>

      <tr> <td><strong>Job ID : </strong><%= r.job_ID%></td>
      </tr>
    </table>

    <br/>
<div id="nav">
    <li><%= link_to "Apply for this Job", new_jobapplication_path, :method => :get %></li>
<% end%>

<li><%= link_to "Back To Home Page", session[:userHP], :method => :get %></li>
</div>
</div>

app/views/jobs/searchForm.html.erb

<div id="wrap">

<%= bootstrap_form_tag({:controller => 'jobs', :action => 'search', :method => 'get'})  do |f| %>
    <%= f.text_field :keyword, value: params[:keyword], style: '', placeholder: 'Type Here...' %>
    <br/>
    <%= f.check_box(:one, label: "Employee") %>
    <%= f.check_box(:two, label: "Job Title") %>
    <%= f.check_box(:three, label: "Job Tags") %>

    <%= f.submit "Search" %>
<% end %>


</br>
  <div id="nav">
<li><%= link_to "Back To Home Page", session[:userHP], :method => :get %></li>
    </div>
    </div>

app/views/jobs/searchFormPublic.html.erb

<div id="wrap">
<%= form_tag({:controller => 'jobs', :action => 'searchPublic'}, {:method => 'get'})  do |s| %>
    <%= label_tag(:keyword,"Search") %>
    <%= text_field_tag :keyword, params[:keyword] %>
    <br/>
    <%= check_box_tag(:one) %>
    <%= label_tag(:one,"Employee") %>
    <%= check_box_tag(:two) %>
    <%= label_tag(:two,"Job Title") %>
    <%= check_box_tag(:three) %>
    <%= label_tag(:three,"Job Tags") %>

    <%= submit_tag "Search" %>
<% end %>


</br>
  <div id="nav">
<li><%= link_to "Home Page", root_path, :method => :get %></li>
      </div>
    </div>

app/views/jobs/searchPublic.html.erb

<div id="wrap">

  <%= table_for @job, class: 'table' do |t| %>
    <% t.column :emp_name, 'Company Name' %>
    <% t.column :title, 'Job Title' %>
    <% t.column :job_ID, 'Job ID' %>
  <% end %>

<br/>

  <div id="nav">
<li><%= link_to "SignIn to Apply!!!", new_session_path, :method => :get %></li>
      </div>
    </div>

app/views/jobs/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<div id="wrap">
  <div id="header">
<h1>
 <%= @job.emp_name %>
</h1>
    </div>
<h4><%= @job.job_ID %></h4>

</br>
<p><%= @job.title %></p>

</br>
  <div id="nav">
<%= link_to "Post another Job!", new_job_path %>
</div>
    </div>
</body>
</html>