config/routes.rb
Rails.application.routes.draw do

  resources :categories

  get 'employersessions/new'

  match '/postJobs' => 'jobs#new', via: :post
  match '/signup' => 'users#new', via: :post
  match '/signin' => 'sessions#new', via: :get
  match '/signout' => 'sessions#destroy', via: :delete
  match '/searchJobs' => 'jobs#search', via: :get
  match '/searchForm' => 'jobs#searchForm', via: :get
  match '/jobList' => 'jobs#indexUser', via: :get
  match '/addEmp' => 'employers#new', via: :get
  match '/viewJobApplicants' => 'jobapplications#indexEmp', via: :get
  match '/admin/signup' => 'admins#new', via: :get
  match '/admin/signin' => 'admin_sessions#new', via: :get
  match '/admin/signout' => 'admin_sessions#destroy', via: :delete
  match '/searchPublic' => 'jobs#searchFormPublic', via: :get
  match '/searchPublicJobs' => 'jobs#searchPublic', via: :get
  match '/recommed'=>'jobs#recommend',via: :get

  root 'home#index'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :jobs
  resources :jobapplications
  resources :employers
  resources :employersessions, :only => [:new, :create, :destroy]
  resources :admins
  resources :admin_sessions, :only => [:new, :create, :destroy]
  resources :home

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="wrap">
<div id="header"><h1>Welcome to THE Job Portal !!</h1></div>
<div id="sidebar">
<ul>
<li><%= link_to "ADMIN LOGIN", new_admin_session_path, :method => :get %></li>
<br/>
<li><%= link_to "EMPLOYER LOGIN", new_employersession_path , :method => :get %></li>
  <br/>
  <li><%= link_to "JOB SEEKER LOGIN", new_session_path , :method => :get %></li>
  <br/>
<li><%= link_to "Search Publically visible Jobs", searchPublic_path , :method => :get %></li>
  <br/>
</ul>
</div>
</div>