config/routes.rb
Rails.application.routes.draw do

  resources :categories

  get 'employersessions/new'

  match '/postJobs' => 'jobs#new', via: :post
  match '/signup' => 'users#new', via: :post
  match '/signin' => 'sessions#new', via: :get
  match '/signout' => 'sessions#destroy', via: :delete
  match '/searchJobs' => 'jobs#search', via: :get
  match '/searchForm' => 'jobs#searchForm', via: :get
  match '/jobList' => 'jobs#indexUser', via: :get
  match '/addEmp' => 'employers#new', via: :get
  match '/viewJobApplicants' => 'jobapplications#indexEmp', via: :get
  match '/admin/signup' => 'admins#new', via: :get
  match '/admin/signin' => 'admin_sessions#new', via: :get
  match '/admin/signout' => 'admin_sessions#destroy', via: :delete
  match '/searchPublic' => 'jobs#searchFormPublic', via: :get
  match '/searchPublicJobs' => 'jobs#searchPublic', via: :get
  match '/recommed'=>'jobs#recommend',via: :get

  root 'home#index'

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :jobs
  resources :jobapplications
  resources :employers
  resources :employersessions, :only => [:new, :create, :destroy]
  resources :admins
  resources :admin_sessions, :only => [:new, :create, :destroy]
  resources :home

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to session[:admin], notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category)

    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>

<%= simple_form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.input :submit %>
  </div>
<% end %>
</body>
</html>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
</head>
<body>
<div id="wrap">
  <div id="header">


  <h1>All Job Categories</h1></div>
<div id="sidebar">
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><li><%=category.category %></li></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<div id="nav">
<%= link_to 'Post a Job', new_job_path %>
</div>
    </div>
</body>
</html>

app/views/categories/new.html.erb
<div id="wrap">
  <div id="header">
    <h1>Add a Category</h1>
  </div>

  <%= simple_form_for(@category) do |f| %>
      <%= f.input :category, placeholder: 'Enter here...' %>
      <%= f.button :submit, "Add a Category" %>
  <% end %>

  <br/>
  <div id="nav">
    <li><%= link_to "Back To Home Page", session[:admin], :method => :get %></li>
    </div>
</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>